ALTER TYPE "ContentFormat" ADD VALUE IF NOT EXISTS 'MARKDOWN';

ALTER TYPE "DocumentStatus" ADD VALUE IF NOT EXISTS 'DRAFT' BEFORE 'ACTIVE';

ALTER TYPE "DocumentSourceType" ADD VALUE IF NOT EXISTS 'USER_CREATED' BEFORE 'UPLOAD_DOCX';
ALTER TYPE "DocumentSourceType" ADD VALUE IF NOT EXISTS 'MIGRATED_DOCUMENT' AFTER 'MCP_CREATED';
ALTER TYPE "DocumentSourceType" ADD VALUE IF NOT EXISTS 'MIGRATED_REQUIREMENT' AFTER 'MCP_CREATED';

ALTER TYPE "DocumentChangeType" ADD VALUE IF NOT EXISTS 'CONVERTED_TO_REQUIREMENT' AFTER 'DELETED';
ALTER TYPE "DocumentChangeType" ADD VALUE IF NOT EXISTS 'CANCELLED_REQUIREMENT' AFTER 'DELETED';
