import { z } from "zod";
import {
  ActionFormFieldIdPathParamsSchema,
  AttachmentIdPathParamsSchema,
  BugIdPathParamsSchema,
  EmptyObjectSchema,
  IdPathParamsSchema,
  MemberIdPathParamsSchema,
  OrganizationIdPathParamsSchema,
  RequirementIdPathParamsSchema,
  SpaceIdPathParamsSchema,
  VersionIdPathParamsSchema,
  WorkItemIdPathParamsSchema,
  WorkflowActionIdPathParamsSchema,
  WorkflowIdPathParamsSchema,
  WorkflowStateIdPathParamsSchema,
  WorkflowVersionIdPathParamsSchema,
} from "./common.ts";
import {
  ChangePasswordRequestSchema,
  ChangePasswordResponseSchema,
  GetAuthSessionQuerySchema,
  GetAuthSessionResponseSchema,
  LoginRequestSchema,
  LoginResponseSchema,
  LogoutRequestSchema,
  LogoutResponseSchema,
  RegisterRequestSchema,
  RegisterResponseSchema,
} from "./auth.ts";
import {
  AddOrganizationMemberRequestSchema,
  AddOrganizationMemberResponseSchema,
  CreateOrganizationRequestSchema,
  CreateOrganizationResponseSchema,
  GetOrganizationResponseSchema,
  ListOrganizationMembersQuerySchema,
  ListOrganizationMembersResponseSchema,
  ListOrganizationsQuerySchema,
  ListOrganizationsResponseSchema,
  UpdateOrganizationMemberRequestSchema,
  UpdateOrganizationMemberResponseSchema,
  UpdateOrganizationRequestSchema,
  UpdateOrganizationResponseSchema,
} from "./organization.ts";
import {
  AddSpaceMemberRequestSchema,
  AddSpaceMemberResponseSchema,
  CreateSpaceRequestSchema,
  CreateSpaceResponseSchema,
  GetSpaceResponseSchema,
  ListSpaceMembersQuerySchema,
  ListSpaceMembersResponseSchema,
  ListSpacesQuerySchema,
  ListSpacesResponseSchema,
  UpdateSpaceMemberRequestSchema,
  UpdateSpaceMemberResponseSchema,
  UpdateSpaceRequestSchema,
  UpdateSpaceResponseSchema,
} from "./space.ts";
import {
  CreateVersionRequestSchema,
  CreateVersionResponseSchema,
  GetVersionResponseSchema,
  ListVersionsQuerySchema,
  ListVersionsResponseSchema,
  UpdateVersionRequestSchema,
  UpdateVersionResponseSchema,
} from "./version.ts";
import {
  CreateRequirementDraftRequestSchema,
  CreateRequirementDraftResponseSchema,
  DeleteRequirementDraftResponseSchema,
  GetRequirementResponseSchema,
  RequirementListQuerySchema,
  ListRequirementsResponseSchema,
  UpdateRequirementRequestSchema,
  UpdateRequirementResponseSchema,
} from "./requirement.ts";
import {
  AcceptIntakeItemResponseSchema,
  ConvertIntakeItemToWorkItemsRequestSchema,
  ConvertIntakeItemToWorkItemsResponseSchema,
  CreateIntakeItemRequestSchema,
  CreateIntakeItemResponseSchema,
  DeferIntakeItemResponseSchema,
  GetIntakeItemResponseSchema,
  IntakeItemListQuerySchema,
  ListIntakeItemsResponseSchema,
  RejectIntakeItemResponseSchema,
  UpdateIntakeItemRequestSchema,
  UpdateIntakeItemResponseSchema,
} from "./intake.ts";
import {
  BugListQuerySchema,
  CreateBugRequestSchema,
  CreateBugResponseSchema,
  CreateWorkItemRequestSchema,
  CreateWorkItemResponseSchema,
  GetBugResponseSchema,
  GetWorkItemResponseSchema,
  ListBugsResponseSchema,
  ListWorkItemsResponseSchema,
  UpdateBugRequestSchema,
  UpdateBugResponseSchema,
  UpdateWorkItemRequestSchema,
  UpdateWorkItemResponseSchema,
  WorkItemListQuerySchema,
} from "./work-item.ts";
import {
  AttachmentListQuerySchema,
  CreateAttachmentRequestSchema,
  CreateAttachmentResponseSchema,
  GetAttachmentDownloadUrlResponseSchema,
  ListAttachmentsResponseSchema,
  PresignAttachmentRequestSchema,
  PresignAttachmentResponseSchema,
} from "./attachment.ts";
import {
  CommentQuerySchema,
  CreateCommentRequestSchema,
  CreateCommentResponseSchema,
  ListCommentsResponseSchema,
  TimelineQuerySchema,
  TimelineResponseSchema,
  WorkItemTimelineQuerySchema,
} from "./timeline.ts";
import {
  CreateActionFormFieldRequestSchema,
  CreateActionFormFieldResponseSchema,
  CreateWorkflowActionRequestSchema,
  CreateWorkflowActionResponseSchema,
  CreateWorkflowBindingRequestSchema,
  CreateWorkflowBindingResponseSchema,
  CreateWorkflowDefinitionRequestSchema,
  CreateWorkflowDefinitionResponseSchema,
  CreateWorkflowStateRequestSchema,
  CreateWorkflowStateResponseSchema,
  CreateWorkflowVersionRequestSchema,
  CreateWorkflowVersionResponseSchema,
  DeleteActionFormFieldResponseSchema,
  DeleteWorkflowActionResponseSchema,
  DeleteWorkflowStateResponseSchema,
  ExecuteActionRequestSchema,
  GetWorkflowDefinitionResponseSchema,
  GetWorkflowVersionResponseSchema,
  ListWorkflowBindingsQuerySchema,
  ListWorkflowBindingsResponseSchema,
  ListWorkflowsQuerySchema,
  ListWorkflowsResponseSchema,
  ListWorkflowVersionsQuerySchema,
  ListWorkflowVersionsResponseSchema,
  PublishWorkflowVersionRequestSchema,
  PublishWorkflowVersionResponseSchema,
  UpdateActionFormFieldRequestSchema,
  UpdateActionFormFieldResponseSchema,
  UpdateWorkflowActionRequestSchema,
  UpdateWorkflowActionResponseSchema,
  UpdateWorkflowBindingRequestSchema,
  UpdateWorkflowBindingResponseSchema,
  UpdateWorkflowDefinitionRequestSchema,
  UpdateWorkflowDefinitionResponseSchema,
  UpdateWorkflowStateRequestSchema,
  UpdateWorkflowStateResponseSchema,
  UpdateWorkflowVersionRequestSchema,
  UpdateWorkflowVersionResponseSchema,
} from "./workflow.ts";
import {
  UpdateUserPreferencesRequestSchema,
  UpdateUserPreferencesResponseSchema,
} from "./user.ts";
import {
  GetMyWorkbenchViewResponseSchema,
  GetSpaceExceptionsViewResponseSchema,
  GetSpaceOverviewViewResponseSchema,
  GetVersionBoardViewResponseSchema,
  SpaceExceptionsViewQuerySchema,
  SpaceOverviewViewQuerySchema,
  VersionBoardViewQuerySchema,
  WorkbenchViewQuerySchema,
} from "./view.ts";

export type HttpMethod = "get" | "post" | "patch" | "delete";

export type ApiEndpointContract = {
  operationId: string;
  method: HttpMethod;
  path: string;
  tags: readonly string[];
  summary: string;
  pathSchema: z.ZodType;
  querySchema: z.ZodType;
  requestSchema: z.ZodType;
  responseSchema: z.ZodType;
  errorCodes: readonly string[];
};

const authErrors = ["UNAUTHORIZED", "INVALID_CREDENTIALS", "RATE_LIMITED"];
const organizationErrors = [
  "UNAUTHORIZED",
  "ORGANIZATION_NOT_FOUND",
  "ORGANIZATION_ACCESS_DENIED",
  "LAST_ORGANIZATION_OWNER_REQUIRED",
  "CROSS_ORGANIZATION_ACCESS_DENIED",
];
const addOrganizationMemberErrors = [
  ...organizationErrors,
  "VALIDATION_ERROR",
  "NOT_FOUND",
  "CONFLICT",
];
const updateOrganizationMemberErrors = [
  ...organizationErrors,
  "VALIDATION_ERROR",
  "ORGANIZATION_MEMBER_NOT_FOUND",
];
const spaceErrors = [
  ...organizationErrors,
  "SPACE_NOT_FOUND",
  "SPACE_ACCESS_DENIED",
  "SPACE_MEMBER_MUST_BELONG_TO_ORGANIZATION",
  "SPACE_MEMBER_NOT_FOUND",
];
const createVersionErrors = [...spaceErrors, "VALIDATION_ERROR", "CONFLICT"];
const versionByIdErrors = [...spaceErrors, "NOT_FOUND", "VALIDATION_ERROR"];
const requirementReferenceErrors = [
  ...spaceErrors,
  "NOT_FOUND",
  "VALIDATION_ERROR",
];
const requirementItemErrors = [
  ...spaceErrors,
  "REQUIREMENT_NOT_FOUND",
  "VALIDATION_ERROR",
];
const workflowErrors = [
  ...spaceErrors,
  "WORKFLOW_NOT_FOUND",
  "WORKFLOW_VERSION_NOT_FOUND",
  "WORKFLOW_VERSION_ALREADY_PUBLISHED",
  "WORKFLOW_VERSION_INVALID",
  "WORKFLOW_PUBLISH_VALIDATION_FAILED",
  "VALIDATION_ERROR",
  "CONFLICT",
  "NOT_FOUND",
];
const executeActionErrors = [
  ...workflowErrors,
  "WORK_ITEM_NOT_FOUND",
  "WORKFLOW_ACTION_NOT_AVAILABLE",
  "WORKFLOW_ACTION_STATE_CONFLICT",
  "WORKFLOW_ACTION_PERMISSION_DENIED",
  "WORKFLOW_ACTION_FORM_INVALID",
  "WORKFLOW_ACTION_COMMENT_REQUIRED",
  "SPACE_MEMBER_INVALID",
];
const linkedTargetErrors = [
  "NOT_FOUND",
  "REQUIREMENT_NOT_FOUND",
  "INTAKE_ITEM_NOT_FOUND",
];
const traceVersionErrors = [
  "TRACE_VERSION_CONFLICT",
  "TRACE_VERSION_CHANGE_REQUIRES_CASCADE",
  "TRACE_CASCADE_CONFLICT",
];
const targetErrors = [
  "SPACE_NOT_FOUND",
  ...linkedTargetErrors,
  "WORK_ITEM_NOT_FOUND",
];
const intakeItemErrors = [
  ...spaceErrors,
  "INTAKE_ITEM_NOT_FOUND",
  "VALIDATION_ERROR",
];
const intakeReferenceErrors = [
  ...intakeItemErrors,
  "NOT_FOUND",
  "REQUIREMENT_NOT_FOUND",
  ...traceVersionErrors,
];
const workItemErrors = [
  ...spaceErrors,
  "WORK_ITEM_NOT_FOUND",
  "VALIDATION_ERROR",
];
const workItemReferenceErrors = [
  ...workItemErrors,
  ...linkedTargetErrors,
  ...traceVersionErrors,
  "WORKFLOW_VERSION_NOT_FOUND",
];
const bugReferenceErrors = workItemReferenceErrors;
const targetEndpointErrors = Array.from(
  new Set([...spaceErrors, ...targetErrors, "VALIDATION_ERROR"]),
);
const attachmentTargetErrors = [
  ...spaceErrors,
  "ATTACHMENT_TARGET_NOT_FOUND",
  "VALIDATION_ERROR",
];
const attachmentUploadErrors = [
  ...attachmentTargetErrors,
  "ATTACHMENT_LIMIT_EXCEEDED",
  "FILE_TOO_LARGE",
  "UNSUPPORTED_MIME_TYPE",
];
const viewErrors = [...spaceErrors, "VALIDATION_ERROR"];

function endpoint(contract: ApiEndpointContract): ApiEndpointContract {
  return contract;
}

export const apiContracts = [
  endpoint({
    operationId: "register",
    method: "post",
    path: "/auth/register",
    tags: ["auth"],
    summary: "Register by username and password",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: RegisterRequestSchema,
    responseSchema: RegisterResponseSchema,
    errorCodes: ["RATE_LIMITED", "VALIDATION_ERROR", "CONFLICT"],
  }),
  endpoint({
    operationId: "login",
    method: "post",
    path: "/auth/login",
    tags: ["auth"],
    summary: "Login by username and password",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: LoginRequestSchema,
    responseSchema: LoginResponseSchema,
    errorCodes: authErrors,
  }),
  endpoint({
    operationId: "logout",
    method: "post",
    path: "/auth/logout",
    tags: ["auth"],
    summary: "Revoke current session",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: LogoutRequestSchema,
    responseSchema: LogoutResponseSchema,
    errorCodes: ["UNAUTHORIZED"],
  }),
  endpoint({
    operationId: "getAuthSession",
    method: "get",
    path: "/auth/session",
    tags: ["auth"],
    summary: "Get app shell session",
    pathSchema: EmptyObjectSchema,
    querySchema: GetAuthSessionQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetAuthSessionResponseSchema,
    errorCodes: ["UNAUTHORIZED"],
  }),
  endpoint({
    operationId: "updateUserPreferences",
    method: "patch",
    path: "/users/me/preferences",
    tags: ["users"],
    summary: "Update current user preferences",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateUserPreferencesRequestSchema,
    responseSchema: UpdateUserPreferencesResponseSchema,
    errorCodes: ["UNAUTHORIZED", "VALIDATION_ERROR"],
  }),
  endpoint({
    operationId: "changePassword",
    method: "patch",
    path: "/users/me/password",
    tags: ["users"],
    summary: "Change current user password",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: ChangePasswordRequestSchema,
    responseSchema: ChangePasswordResponseSchema,
    errorCodes: ["UNAUTHORIZED", "INVALID_CREDENTIALS", "VALIDATION_ERROR"],
  }),
  endpoint({
    operationId: "listOrganizations",
    method: "get",
    path: "/organizations",
    tags: ["organizations"],
    summary: "List organizations current user can access",
    pathSchema: EmptyObjectSchema,
    querySchema: ListOrganizationsQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListOrganizationsResponseSchema,
    errorCodes: ["UNAUTHORIZED"],
  }),
  endpoint({
    operationId: "createOrganization",
    method: "post",
    path: "/organizations",
    tags: ["organizations"],
    summary: "Create organization and initialize owner membership",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateOrganizationRequestSchema,
    responseSchema: CreateOrganizationResponseSchema,
    errorCodes: [
      "UNAUTHORIZED",
      "RATE_LIMITED",
      "VALIDATION_ERROR",
      "CONFLICT",
    ],
  }),
  endpoint({
    operationId: "getOrganization",
    method: "get",
    path: "/organizations/{organizationId}",
    tags: ["organizations"],
    summary: "Get organization",
    pathSchema: OrganizationIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetOrganizationResponseSchema,
    errorCodes: organizationErrors,
  }),
  endpoint({
    operationId: "updateOrganization",
    method: "patch",
    path: "/organizations/{organizationId}",
    tags: ["organizations"],
    summary: "Update organization",
    pathSchema: OrganizationIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateOrganizationRequestSchema,
    responseSchema: UpdateOrganizationResponseSchema,
    errorCodes: organizationErrors,
  }),
  endpoint({
    operationId: "listOrganizationMembers",
    method: "get",
    path: "/organizations/{organizationId}/members",
    tags: ["organization-members"],
    summary: "List organization members",
    pathSchema: OrganizationIdPathParamsSchema,
    querySchema: ListOrganizationMembersQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListOrganizationMembersResponseSchema,
    errorCodes: organizationErrors,
  }),
  endpoint({
    operationId: "addOrganizationMember",
    method: "post",
    path: "/organizations/{organizationId}/members",
    tags: ["organization-members"],
    summary: "Add organization member",
    pathSchema: OrganizationIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: AddOrganizationMemberRequestSchema,
    responseSchema: AddOrganizationMemberResponseSchema,
    errorCodes: addOrganizationMemberErrors,
  }),
  endpoint({
    operationId: "updateOrganizationMember",
    method: "patch",
    path: "/organizations/{organizationId}/members/{memberId}",
    tags: ["organization-members"],
    summary: "Update organization member",
    pathSchema: OrganizationIdPathParamsSchema.merge(MemberIdPathParamsSchema),
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateOrganizationMemberRequestSchema,
    responseSchema: UpdateOrganizationMemberResponseSchema,
    errorCodes: updateOrganizationMemberErrors,
  }),
  endpoint({
    operationId: "listSpaces",
    method: "get",
    path: "/organizations/{organizationId}/spaces",
    tags: ["spaces"],
    summary: "List spaces in organization",
    pathSchema: OrganizationIdPathParamsSchema,
    querySchema: ListSpacesQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListSpacesResponseSchema,
    errorCodes: organizationErrors,
  }),
  endpoint({
    operationId: "createSpace",
    method: "post",
    path: "/organizations/{organizationId}/spaces",
    tags: ["spaces"],
    summary: "Create space in organization",
    pathSchema: OrganizationIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateSpaceRequestSchema,
    responseSchema: CreateSpaceResponseSchema,
    errorCodes: spaceErrors,
  }),
  endpoint({
    operationId: "getSpace",
    method: "get",
    path: "/spaces/{spaceId}",
    tags: ["spaces"],
    summary: "Get space",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetSpaceResponseSchema,
    errorCodes: spaceErrors,
  }),
  endpoint({
    operationId: "updateSpace",
    method: "patch",
    path: "/spaces/{spaceId}",
    tags: ["spaces"],
    summary: "Update space",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateSpaceRequestSchema,
    responseSchema: UpdateSpaceResponseSchema,
    errorCodes: spaceErrors,
  }),
  endpoint({
    operationId: "getMyWorkbenchView",
    method: "get",
    path: "/views/my-workbench",
    tags: ["views"],
    summary: "Get M4 my workbench view",
    pathSchema: EmptyObjectSchema,
    querySchema: WorkbenchViewQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetMyWorkbenchViewResponseSchema,
    errorCodes: viewErrors,
  }),
  endpoint({
    operationId: "getSpaceOverview",
    method: "get",
    path: "/views/spaces/{spaceId}/overview",
    tags: ["views"],
    summary: "Get M4 space overview view",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: SpaceOverviewViewQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetSpaceOverviewViewResponseSchema,
    errorCodes: viewErrors,
  }),
  endpoint({
    operationId: "getSpaceExceptionsView",
    method: "get",
    path: "/views/spaces/{spaceId}/exceptions",
    tags: ["views"],
    summary: "Get M4 space exceptions view",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: SpaceExceptionsViewQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetSpaceExceptionsViewResponseSchema,
    errorCodes: viewErrors,
  }),
  endpoint({
    operationId: "listSpaceMembers",
    method: "get",
    path: "/spaces/{spaceId}/members",
    tags: ["space-members"],
    summary: "List space members",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: ListSpaceMembersQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListSpaceMembersResponseSchema,
    errorCodes: spaceErrors,
  }),
  endpoint({
    operationId: "addSpaceMember",
    method: "post",
    path: "/spaces/{spaceId}/members",
    tags: ["space-members"],
    summary: "Add space member",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: AddSpaceMemberRequestSchema,
    responseSchema: AddSpaceMemberResponseSchema,
    errorCodes: spaceErrors,
  }),
  endpoint({
    operationId: "updateSpaceMember",
    method: "patch",
    path: "/spaces/{spaceId}/members/{memberId}",
    tags: ["space-members"],
    summary: "Update space member",
    pathSchema: SpaceIdPathParamsSchema.merge(MemberIdPathParamsSchema),
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateSpaceMemberRequestSchema,
    responseSchema: UpdateSpaceMemberResponseSchema,
    errorCodes: spaceErrors,
  }),
  endpoint({
    operationId: "listVersions",
    method: "get",
    path: "/spaces/{spaceId}/versions",
    tags: ["versions"],
    summary: "List versions",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: ListVersionsQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListVersionsResponseSchema,
    errorCodes: spaceErrors,
  }),
  endpoint({
    operationId: "createVersion",
    method: "post",
    path: "/spaces/{spaceId}/versions",
    tags: ["versions"],
    summary: "Create version",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateVersionRequestSchema,
    responseSchema: CreateVersionResponseSchema,
    errorCodes: createVersionErrors,
  }),
  endpoint({
    operationId: "getVersion",
    method: "get",
    path: "/versions/{versionId}",
    tags: ["versions"],
    summary: "Get version",
    pathSchema: VersionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetVersionResponseSchema,
    errorCodes: versionByIdErrors,
  }),
  endpoint({
    operationId: "getVersionBoardView",
    method: "get",
    path: "/views/versions/{versionId}/board",
    tags: ["views"],
    summary: "Get M4 version board view",
    pathSchema: VersionIdPathParamsSchema,
    querySchema: VersionBoardViewQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetVersionBoardViewResponseSchema,
    errorCodes: [...versionByIdErrors, "VALIDATION_ERROR"],
  }),
  endpoint({
    operationId: "updateVersion",
    method: "patch",
    path: "/versions/{versionId}",
    tags: ["versions"],
    summary: "Update version",
    pathSchema: VersionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateVersionRequestSchema,
    responseSchema: UpdateVersionResponseSchema,
    errorCodes: [...versionByIdErrors, "CONFLICT"],
  }),
  endpoint({
    operationId: "listRequirements",
    method: "get",
    path: "/spaces/{spaceId}/requirements",
    tags: ["requirements"],
    summary: "List requirements",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: RequirementListQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListRequirementsResponseSchema,
    errorCodes: requirementReferenceErrors,
  }),
  endpoint({
    operationId: "createRequirementDraft",
    method: "post",
    path: "/spaces/{spaceId}/requirements",
    tags: ["requirements"],
    summary: "Create requirement draft",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateRequirementDraftRequestSchema,
    responseSchema: CreateRequirementDraftResponseSchema,
    errorCodes: [...requirementReferenceErrors, "DRAFT_REQUIREMENT_REQUIRED"],
  }),
  endpoint({
    operationId: "getRequirement",
    method: "get",
    path: "/requirements/{requirementId}",
    tags: ["requirements"],
    summary: "Get requirement",
    pathSchema: RequirementIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetRequirementResponseSchema,
    errorCodes: requirementItemErrors,
  }),
  endpoint({
    operationId: "updateRequirement",
    method: "patch",
    path: "/requirements/{requirementId}",
    tags: ["requirements"],
    summary: "Save or archive requirement",
    pathSchema: RequirementIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateRequirementRequestSchema,
    responseSchema: UpdateRequirementResponseSchema,
    errorCodes: [...requirementItemErrors, "NOT_FOUND", ...traceVersionErrors],
  }),
  endpoint({
    operationId: "deleteRequirementDraft",
    method: "delete",
    path: "/requirements/{requirementId}",
    tags: ["requirements"],
    summary: "Delete an empty requirement draft",
    pathSchema: RequirementIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: DeleteRequirementDraftResponseSchema,
    errorCodes: [...requirementItemErrors, "DRAFT_REQUIREMENT_REQUIRED"],
  }),
  endpoint({
    operationId: "listIntakeItems",
    method: "get",
    path: "/spaces/{spaceId}/intake-items",
    tags: ["intake"],
    summary: "List intake items",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: IntakeItemListQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListIntakeItemsResponseSchema,
    errorCodes: intakeReferenceErrors,
  }),
  endpoint({
    operationId: "createIntakeItem",
    method: "post",
    path: "/spaces/{spaceId}/intake-items",
    tags: ["intake"],
    summary: "Create intake item",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateIntakeItemRequestSchema,
    responseSchema: CreateIntakeItemResponseSchema,
    errorCodes: intakeReferenceErrors,
  }),
  endpoint({
    operationId: "getIntakeItem",
    method: "get",
    path: "/intake-items/{id}",
    tags: ["intake"],
    summary: "Get intake item",
    pathSchema: IdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetIntakeItemResponseSchema,
    errorCodes: intakeItemErrors,
  }),
  endpoint({
    operationId: "updateIntakeItem",
    method: "patch",
    path: "/intake-items/{id}",
    tags: ["intake"],
    summary: "Update intake item",
    pathSchema: IdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateIntakeItemRequestSchema,
    responseSchema: UpdateIntakeItemResponseSchema,
    errorCodes: intakeReferenceErrors,
  }),
  endpoint({
    operationId: "acceptIntakeItem",
    method: "post",
    path: "/intake-items/{id}/accept",
    tags: ["intake"],
    summary: "Accept intake item",
    pathSchema: IdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: AcceptIntakeItemResponseSchema,
    errorCodes: [...intakeItemErrors, "INTAKE_ITEM_ALREADY_CONVERTED"],
  }),
  endpoint({
    operationId: "deferIntakeItem",
    method: "post",
    path: "/intake-items/{id}/defer",
    tags: ["intake"],
    summary: "Defer intake item",
    pathSchema: IdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: DeferIntakeItemResponseSchema,
    errorCodes: [...intakeItemErrors, "INTAKE_ITEM_ALREADY_CONVERTED"],
  }),
  endpoint({
    operationId: "rejectIntakeItem",
    method: "post",
    path: "/intake-items/{id}/reject",
    tags: ["intake"],
    summary: "Reject intake item",
    pathSchema: IdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: RejectIntakeItemResponseSchema,
    errorCodes: [...intakeItemErrors, "INTAKE_ITEM_ALREADY_CONVERTED"],
  }),
  endpoint({
    operationId: "convertIntakeItemToWorkItems",
    method: "post",
    path: "/intake-items/{id}/convert-to-work-items",
    tags: ["intake"],
    summary: "Convert accepted intake item to work items",
    pathSchema: IdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: ConvertIntakeItemToWorkItemsRequestSchema,
    responseSchema: ConvertIntakeItemToWorkItemsResponseSchema,
    errorCodes: [
      ...intakeItemErrors,
      "NOT_FOUND",
      "REQUIREMENT_NOT_FOUND",
      "WORKFLOW_VERSION_NOT_FOUND",
      "INTAKE_ITEM_NOT_ACCEPTED",
      "INTAKE_ITEM_ALREADY_CONVERTED",
    ],
  }),
  endpoint({
    operationId: "listWorkItems",
    method: "get",
    path: "/spaces/{spaceId}/work-items",
    tags: ["work-items"],
    summary: "List work items",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: WorkItemListQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListWorkItemsResponseSchema,
    errorCodes: workItemReferenceErrors,
  }),
  endpoint({
    operationId: "createWorkItem",
    method: "post",
    path: "/spaces/{spaceId}/work-items",
    tags: ["work-items"],
    summary: "Create work item",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateWorkItemRequestSchema,
    responseSchema: CreateWorkItemResponseSchema,
    errorCodes: workItemReferenceErrors,
  }),
  endpoint({
    operationId: "getWorkItem",
    method: "get",
    path: "/work-items/{workItemId}",
    tags: ["work-items"],
    summary: "Get work item",
    pathSchema: WorkItemIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetWorkItemResponseSchema,
    errorCodes: workItemErrors,
  }),
  endpoint({
    operationId: "updateWorkItem",
    method: "patch",
    path: "/work-items/{workItemId}",
    tags: ["work-items"],
    summary: "Update work item",
    pathSchema: WorkItemIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateWorkItemRequestSchema,
    responseSchema: UpdateWorkItemResponseSchema,
    errorCodes: workItemReferenceErrors,
  }),
  endpoint({
    operationId: "listBugs",
    method: "get",
    path: "/spaces/{spaceId}/bugs",
    tags: ["bugs"],
    summary: "List bugs",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: BugListQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListBugsResponseSchema,
    errorCodes: bugReferenceErrors,
  }),
  endpoint({
    operationId: "createBug",
    method: "post",
    path: "/spaces/{spaceId}/bugs",
    tags: ["bugs"],
    summary: "Create bug",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateBugRequestSchema,
    responseSchema: CreateBugResponseSchema,
    errorCodes: bugReferenceErrors,
  }),
  endpoint({
    operationId: "getBug",
    method: "get",
    path: "/bugs/{bugId}",
    tags: ["bugs"],
    summary: "Get bug detail",
    pathSchema: BugIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetBugResponseSchema,
    errorCodes: workItemErrors,
  }),
  endpoint({
    operationId: "updateBug",
    method: "patch",
    path: "/bugs/{bugId}",
    tags: ["bugs"],
    summary: "Update bug detail",
    pathSchema: BugIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateBugRequestSchema,
    responseSchema: UpdateBugResponseSchema,
    errorCodes: bugReferenceErrors,
  }),
  endpoint({
    operationId: "listWorkflows",
    method: "get",
    path: "/spaces/{spaceId}/workflows",
    tags: ["workflows"],
    summary: "List workflow definitions",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: ListWorkflowsQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListWorkflowsResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "createWorkflow",
    method: "post",
    path: "/spaces/{spaceId}/workflows",
    tags: ["workflows"],
    summary: "Create workflow definition",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateWorkflowDefinitionRequestSchema,
    responseSchema: CreateWorkflowDefinitionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "getWorkflow",
    method: "get",
    path: "/workflows/{workflowId}",
    tags: ["workflows"],
    summary: "Get workflow definition",
    pathSchema: WorkflowIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetWorkflowDefinitionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "updateWorkflow",
    method: "patch",
    path: "/workflows/{workflowId}",
    tags: ["workflows"],
    summary: "Update workflow definition",
    pathSchema: WorkflowIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateWorkflowDefinitionRequestSchema,
    responseSchema: UpdateWorkflowDefinitionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "listWorkflowVersions",
    method: "get",
    path: "/workflows/{workflowId}/versions",
    tags: ["workflow-versions"],
    summary: "List workflow versions",
    pathSchema: WorkflowIdPathParamsSchema,
    querySchema: ListWorkflowVersionsQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListWorkflowVersionsResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "createWorkflowVersion",
    method: "post",
    path: "/workflows/{workflowId}/versions",
    tags: ["workflow-versions"],
    summary: "Create draft workflow version",
    pathSchema: WorkflowIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateWorkflowVersionRequestSchema,
    responseSchema: CreateWorkflowVersionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "getWorkflowVersion",
    method: "get",
    path: "/workflow-versions/{workflowVersionId}",
    tags: ["workflow-versions"],
    summary: "Get workflow version",
    pathSchema: WorkflowVersionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetWorkflowVersionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "updateWorkflowVersion",
    method: "patch",
    path: "/workflow-versions/{workflowVersionId}",
    tags: ["workflow-versions"],
    summary: "Update workflow version",
    pathSchema: WorkflowVersionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateWorkflowVersionRequestSchema,
    responseSchema: UpdateWorkflowVersionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "publishWorkflowVersion",
    method: "post",
    path: "/workflow-versions/{workflowVersionId}/publish",
    tags: ["workflow-versions"],
    summary: "Publish workflow version",
    pathSchema: WorkflowVersionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: PublishWorkflowVersionRequestSchema,
    responseSchema: PublishWorkflowVersionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "createWorkflowState",
    method: "post",
    path: "/workflow-versions/{workflowVersionId}/states",
    tags: ["workflow-states"],
    summary: "Create workflow state",
    pathSchema: WorkflowVersionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateWorkflowStateRequestSchema,
    responseSchema: CreateWorkflowStateResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "updateWorkflowState",
    method: "patch",
    path: "/workflow-states/{stateId}",
    tags: ["workflow-states"],
    summary: "Update workflow state",
    pathSchema: WorkflowStateIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateWorkflowStateRequestSchema,
    responseSchema: UpdateWorkflowStateResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "deleteWorkflowState",
    method: "delete",
    path: "/workflow-states/{stateId}",
    tags: ["workflow-states"],
    summary: "Delete workflow state",
    pathSchema: WorkflowStateIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: DeleteWorkflowStateResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "createWorkflowAction",
    method: "post",
    path: "/workflow-versions/{workflowVersionId}/actions",
    tags: ["workflow-actions"],
    summary: "Create workflow action",
    pathSchema: WorkflowVersionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateWorkflowActionRequestSchema,
    responseSchema: CreateWorkflowActionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "updateWorkflowAction",
    method: "patch",
    path: "/workflow-actions/{actionId}",
    tags: ["workflow-actions"],
    summary: "Update workflow action",
    pathSchema: WorkflowActionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateWorkflowActionRequestSchema,
    responseSchema: UpdateWorkflowActionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "deleteWorkflowAction",
    method: "delete",
    path: "/workflow-actions/{actionId}",
    tags: ["workflow-actions"],
    summary: "Delete workflow action",
    pathSchema: WorkflowActionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: DeleteWorkflowActionResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "createActionFormField",
    method: "post",
    path: "/workflow-actions/{actionId}/form-fields",
    tags: ["workflow-action-fields"],
    summary: "Create action form field",
    pathSchema: WorkflowActionIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateActionFormFieldRequestSchema,
    responseSchema: CreateActionFormFieldResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "updateActionFormField",
    method: "patch",
    path: "/action-form-fields/{fieldId}",
    tags: ["workflow-action-fields"],
    summary: "Update action form field",
    pathSchema: ActionFormFieldIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateActionFormFieldRequestSchema,
    responseSchema: UpdateActionFormFieldResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "deleteActionFormField",
    method: "delete",
    path: "/action-form-fields/{fieldId}",
    tags: ["workflow-action-fields"],
    summary: "Delete action form field",
    pathSchema: ActionFormFieldIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: DeleteActionFormFieldResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "listWorkflowBindings",
    method: "get",
    path: "/spaces/{spaceId}/workflow-bindings",
    tags: ["workflow-bindings"],
    summary: "List workflow bindings",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: ListWorkflowBindingsQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListWorkflowBindingsResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "createWorkflowBinding",
    method: "post",
    path: "/spaces/{spaceId}/workflow-bindings",
    tags: ["workflow-bindings"],
    summary: "Create workflow binding",
    pathSchema: SpaceIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateWorkflowBindingRequestSchema,
    responseSchema: CreateWorkflowBindingResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "updateWorkflowBinding",
    method: "patch",
    path: "/workflow-bindings/{id}",
    tags: ["workflow-bindings"],
    summary: "Update workflow binding",
    pathSchema: IdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: UpdateWorkflowBindingRequestSchema,
    responseSchema: UpdateWorkflowBindingResponseSchema,
    errorCodes: workflowErrors,
  }),
  endpoint({
    operationId: "executeWorkflowAction",
    method: "post",
    path: "/work-items/{workItemId}/actions/{actionId}/execute",
    tags: ["workflow-actions"],
    summary: "Execute workflow action",
    pathSchema: WorkItemIdPathParamsSchema.merge(
      WorkflowActionIdPathParamsSchema,
    ),
    querySchema: EmptyObjectSchema,
    requestSchema: ExecuteActionRequestSchema,
    responseSchema: GetWorkItemResponseSchema,
    errorCodes: executeActionErrors,
  }),
  endpoint({
    operationId: "listTimeline",
    method: "get",
    path: "/timeline",
    tags: ["timeline"],
    summary: "List timeline events by target",
    pathSchema: EmptyObjectSchema,
    querySchema: TimelineQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: TimelineResponseSchema,
    errorCodes: targetEndpointErrors,
  }),
  endpoint({
    operationId: "listWorkItemTimeline",
    method: "get",
    path: "/work-items/{workItemId}/timeline",
    tags: ["timeline"],
    summary: "List work item timeline",
    pathSchema: WorkItemIdPathParamsSchema,
    querySchema: WorkItemTimelineQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: TimelineResponseSchema,
    errorCodes: workItemErrors,
  }),
  endpoint({
    operationId: "listComments",
    method: "get",
    path: "/comments",
    tags: ["comments"],
    summary: "List comments by target",
    pathSchema: EmptyObjectSchema,
    querySchema: CommentQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListCommentsResponseSchema,
    errorCodes: targetEndpointErrors,
  }),
  endpoint({
    operationId: "createComment",
    method: "post",
    path: "/comments",
    tags: ["comments"],
    summary: "Create comment",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateCommentRequestSchema,
    responseSchema: CreateCommentResponseSchema,
    errorCodes: targetEndpointErrors,
  }),
  endpoint({
    operationId: "listAttachments",
    method: "get",
    path: "/attachments",
    tags: ["attachments"],
    summary: "List attachments by target",
    pathSchema: EmptyObjectSchema,
    querySchema: AttachmentListQuerySchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: ListAttachmentsResponseSchema,
    errorCodes: attachmentTargetErrors,
  }),
  endpoint({
    operationId: "presignAttachment",
    method: "post",
    path: "/attachments/presign",
    tags: ["attachments"],
    summary: "Presign attachment upload",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: PresignAttachmentRequestSchema,
    responseSchema: PresignAttachmentResponseSchema,
    errorCodes: [
      ...attachmentUploadErrors,
      "TARGET_REQUIRED_FOR_ATTACHMENT",
      "DRAFT_REQUIREMENT_REQUIRED",
    ],
  }),
  endpoint({
    operationId: "createAttachment",
    method: "post",
    path: "/attachments",
    tags: ["attachments"],
    summary: "Register uploaded attachment",
    pathSchema: EmptyObjectSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: CreateAttachmentRequestSchema,
    responseSchema: CreateAttachmentResponseSchema,
    errorCodes: [...attachmentUploadErrors, "DRAFT_REQUIREMENT_REQUIRED"],
  }),
  endpoint({
    operationId: "getAttachmentDownloadUrl",
    method: "get",
    path: "/attachments/{attachmentId}/download-url",
    tags: ["attachments"],
    summary: "Get attachment download URL",
    pathSchema: AttachmentIdPathParamsSchema,
    querySchema: EmptyObjectSchema,
    requestSchema: EmptyObjectSchema,
    responseSchema: GetAttachmentDownloadUrlResponseSchema,
    errorCodes: attachmentTargetErrors,
  }),
] as const satisfies readonly ApiEndpointContract[];
