import type { TimelineEvent } from "@project-delivery/shared";
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import type { ReactNode } from "react";
import { describe, expect, it, vi } from "vitest";

import { TimelineEventItem } from "./timeline-event-item";

vi.mock("next-intl", () => ({
  useTranslations: () => {
    const translate = ((key: string) => key) as ((key: string) => string) & {
      has: () => boolean;
    };
    translate.has = () => false;
    return translate;
  },
}));

vi.mock("../../i18n/routing", () => ({
  Link: ({
    children,
    href,
    ...rest
  }: {
    children: ReactNode;
    href: string;
    [key: string]: unknown;
  }) => (
    <a href={String(href)} {...rest}>
      {children}
    </a>
  ),
}));

function makeEvent(overrides: Partial<TimelineEvent> = {}): TimelineEvent {
  return {
    actor: {
      id: "01ARZ3NDEKTSV4RRFFQ69G5FA1",
      name: "admin",
      username: "admin",
    },
    createdAt: "2026-05-20T10:00:00.000Z",
    eventType: "UPDATED",
    id: "01ARZ3NDEKTSV4RRFFQ69G5FA2",
    organizationId: "01ARZ3NDEKTSV4RRFFQ69G5FA3",
    spaceId: "01ARZ3NDEKTSV4RRFFQ69G5FA4",
    target: {
      id: "01ARZ3NDEKTSV4RRFFQ69G5FA5",
      title: "Default task",
      type: "WORK_ITEM",
    },
    ...overrides,
  } as TimelineEvent;
}

function mockOverflow(element: HTMLElement, overflowing: boolean) {
  Object.defineProperties(element, {
    clientHeight: { configurable: true, value: 20 },
    clientWidth: { configurable: true, value: 160 },
    scrollHeight: { configurable: true, value: 20 },
    scrollWidth: { configurable: true, value: overflowing ? 320 : 160 },
  });
}

describe("TimelineEventItem", () => {
  it("shows a tooltip when compact primary text is truncated", async () => {
    const user = userEvent.setup();
    const longTitle =
      "STRAWBERRY_DOCK_gateway_export_result_markdown_attachment_with_a_very_long_name.md";

    render(
      <TimelineEventItem
        density="compact"
        event={makeEvent({
          target: {
            id: "01ARZ3NDEKTSV4RRFFQ69G5FA5",
            title: longTitle,
            type: "WORK_ITEM",
          },
        })}
        href="/work-items?taskId=01ARZ3NDEKTSV4RRFFQ69G5FA5"
        locale="zh-CN"
        translateEventType={(key) => `common.timeline.event.${key}`}
      />,
    );

    const title = screen.getByText(longTitle);
    const tooltipTrigger = title.closest("[data-state]") as HTMLElement;
    expect(tooltipTrigger).toHaveAttribute("data-state", "closed");
    expect(title.closest("a")).toHaveAttribute(
      "href",
      "/work-items?taskId=01ARZ3NDEKTSV4RRFFQ69G5FA5",
    );

    mockOverflow(tooltipTrigger, true);
    await user.hover(tooltipTrigger);
    expect(await screen.findByRole("tooltip")).toHaveTextContent(longTitle);
  });

  it("does not show a tooltip when compact primary text is not truncated", async () => {
    const user = userEvent.setup();

    render(
      <TimelineEventItem
        density="compact"
        event={makeEvent({
          target: {
            id: "01ARZ3NDEKTSV4RRFFQ69G5FA5",
            title: "kkk",
            type: "WORK_ITEM",
          },
        })}
        locale="zh-CN"
        translateEventType={(key) => `common.timeline.event.${key}`}
      />,
    );

    const title = screen.getByText("kkk");
    const tooltipTrigger = title.closest("[data-state]") as HTMLElement;
    mockOverflow(tooltipTrigger, false);

    await user.hover(tooltipTrigger);
    await expect(
      screen.findByRole("tooltip", {}, { timeout: 500 }),
    ).rejects.toThrow();
  });

  it("shows a tooltip when compact detail text is truncated", async () => {
    const user = userEvent.setup();
    const longDetail =
      "text/markdown / 127 KB / generated by import pipeline with additional context";

    render(
      <TimelineEventItem
        density="compact"
        event={makeEvent({ detail: longDetail })}
        locale="zh-CN"
        translateEventType={(key) => `common.timeline.event.${key}`}
      />,
    );

    const detail = screen.getByText(longDetail);
    expect(detail).toHaveClass("truncate");
    expect(detail.closest("[data-state]")).toBe(detail);

    mockOverflow(detail, true);
    await user.hover(detail);
    expect(await screen.findByRole("tooltip")).toHaveTextContent(longDetail);
  });
});
